name = "cf-cloak"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true

# 配置变量：部署后再替换为你的实际值
[vars]
PAGES_ORIGIN = "cloak-pages.pages.dev"
DYNAMIC_ORIGIN = "https://httpbin.org"        # 示例动态源，可换成你的后端
ALLOWED_COUNTRIES = "BR,PT,US"                 # 允许触发动态层的国家代码，逗号分隔

# 绑定 KV（创建后替换 id / preview_id）
[[kv_namespaces]]
binding = "CONFIG"
id = ""              # 生产 ID
preview_id = ""      # 预览 ID

# 如果你已接入自定义域名，可取消注释 routes 并填写
# [[routes]]
# pattern = "example.com/*"
# zone_name = "example.com"